{
 "cells": [
  {
   "cell_type": "markdown",
   "id": "6cdde475-d2e9-4710-b048-ad23ba9e728e",
   "metadata": {},
   "source": [
    "整合_智冠_5478"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 1,
   "id": "a2228840-6b61-44f6-b62a-ea66f1f60a30",
   "metadata": {},
   "outputs": [],
   "source": [
    "# 設定台北時區\n",
    "import os\n",
    "from datetime import datetime\n",
    "import pytz\n",
    "\n",
    "tz = pytz.timezone(\"Asia/Taipei\")\n",
    "now = datetime.now(tz)\n",
    "roc_year = now.year - 1911  # 民國年\n",
    "date = f\"{roc_year}{now.month:02d}{now.day:02d}\"\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 2,
   "id": "1dbea242-371a-4a4e-8ecb-e40f87c54145",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "資料夾'C:\\Users\\trista.huang\\Desktop\\證券日報表\\1150206',已建立!\n"
     ]
    }
   ],
   "source": [
    "#建立新的資料夾\n",
    "path=r\"C:\\Users\\trista.huang\\Desktop\\證券日報表\"\n",
    "folder_path=os.path.join(path,date)\n",
    "if not os.path.exists(folder_path):\n",
    "    os.makedirs(folder_path)\n",
    "    print(f\"資料夾'{folder_path}',已建立!\")\n",
    "else:\n",
    "    print(f\"資料夾'{folder_path}',已存在!\")"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 3,
   "id": "8729e592-470f-4098-8b73-2fc81b935268",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "智冠檔案複製完成！\n"
     ]
    }
   ],
   "source": [
    "#複製新的檔案到資料夾_智冠\n",
    "import shutil\n",
    "base_path = r\"C:\\Users\\trista.huang\\Desktop\\證券日報表\"\n",
    "folder_path = os.path.join(base_path, date)\n",
    "\n",
    "# 原始檔案路徑\n",
    "source_path_sw = os.path.join(base_path, \"1150121\", f\"智冠_1150121.xlsx\")\n",
    "\n",
    "# 目標檔案路徑（複製後的新檔名）\n",
    "target_path_sw = os.path.join(folder_path, f\"智冠_{date}.xlsx\")\n",
    "\n",
    "# 執行複製\n",
    "shutil.copyfile(source_path_sw, target_path_sw)\n",
    "\n",
    "print(\"智冠檔案複製完成！\")"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 4,
   "id": "a0cf1462-6dfe-4168-a4b5-3a07a3fe26e4",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "檔案分頁名稱修改完成\n",
      "原始資料清除完成\n"
     ]
    }
   ],
   "source": [
    "#分頁內容更新\n",
    "import xlwings as xw\n",
    "\n",
    "if not os.path.exists(target_path_sw):\n",
    "    print(\"智冠檔案不存在！\")\n",
    "else:\n",
    "    wb_sw = xw.Book(target_path_sw)\n",
    "    \n",
    "    # 修改分頁名稱\n",
    "    if len(wb_sw.sheets) >= 2:\n",
    "        wb_sw.sheets[0].name = f\"智冠_{date}\"\n",
    "        wb_sw.sheets[1].name = f\"5478_{date}\"\n",
    "        wb_sw.save()\n",
    "        print(\"檔案分頁名稱修改完成\")\n",
    "        \n",
    "        # 清除第一分頁的列表\n",
    "        sheet1 = wb_sw.sheets[0]\n",
    "        sheet1.range('A3').expand('table').clear_contents()\n",
    "        \n",
    "        # 清除第一分頁的外資買賣超表格\n",
    "        sheet2 = wb_sw.sheets[0]\n",
    "        sheet2.range('F4').expand('table').clear_contents()\n",
    "        \n",
    "        #清除第一分頁的截圖\n",
    "        sheet3 = wb_sw.sheets[0]\n",
    "        for shape in sheet3.shapes:\n",
    "            shape.delete()\n",
    "\n",
    "        #清除第一分頁的單日增減變動\n",
    "        sheet4 = wb_sw.sheets[0]\n",
    "        sheet4.range('F13').expand('table').clear_contents()\n",
    "\n",
    "        #清除分點名單\n",
    "        sheet5 = wb_sw.sheets[0]\n",
    "        sheet5.range('I13').expand('table').clear_contents()\n",
    "\n",
    "        #清除第二個分頁的總表\n",
    "        sheet6=wb_sw.sheets[1]\n",
    "        sheet6.range('A3').expand('table').clear_contents()\n",
    "  \n",
    "        print(\"原始資料清除完成\")\n",
    "    else:\n",
    "        print(\"無法執行清除與命名\")\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 5,
   "id": "c736436e-9d75-4577-aace-63325dac9ac1",
   "metadata": {},
   "outputs": [],
   "source": [
    "#爬取券商買賣證券日報表查詢系統（一般交易）\n",
    "from selenium import webdriver\n",
    "from selenium.webdriver.common.keys import Keys\n",
    "from selenium.webdriver.common.by import By\n",
    "import undetected_chromedriver as uc\n",
    "from bs4 import BeautifulSoup\n",
    "#爬取網址\n",
    "options = uc.ChromeOptions()\n",
    "options.add_argument(\"--disable-blink-features=AutomationControlled\")\n",
    "driver = uc.Chrome(version_main=144, options=options)\n",
    "url = \"https://www.tpex.org.tw/zh-tw/mainboard/trading/info/brokerBS.html\"\n",
    "driver.get(url)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 6,
   "id": "036098a0-5b81-414c-8825-e01225662f16",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "下載完成\n"
     ]
    }
   ],
   "source": [
    "#輸入要下載的股票代號\n",
    "import time \n",
    "time.sleep(6)\n",
    "input_section = driver.find_element(By.ID, \"___auto1\")\n",
    "keyword=\"5478\"\n",
    "input_section.send_keys(keyword)\n",
    "download_button = driver.find_element(By.XPATH, '//button[text()=\"下載 CSV (BIG5)\"]')\n",
    "download_button.click()\n",
    "print(\"下載完成\")"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 7,
   "id": "efd54d85-c19c-49ca-aae7-a89310fb5da5",
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/html": [
       "<div>\n",
       "<style scoped>\n",
       "    .dataframe tbody tr th:only-of-type {\n",
       "        vertical-align: middle;\n",
       "    }\n",
       "\n",
       "    .dataframe tbody tr th {\n",
       "        vertical-align: top;\n",
       "    }\n",
       "\n",
       "    .dataframe thead th {\n",
       "        text-align: right;\n",
       "    }\n",
       "</style>\n",
       "<table border=\"1\" class=\"dataframe\">\n",
       "  <thead>\n",
       "    <tr style=\"text-align: right;\">\n",
       "      <th></th>\n",
       "      <th>序號</th>\n",
       "      <th>券商</th>\n",
       "      <th>價格</th>\n",
       "      <th>買進股數</th>\n",
       "      <th>賣出股數</th>\n",
       "    </tr>\n",
       "  </thead>\n",
       "  <tbody>\n",
       "    <tr>\n",
       "      <th>0</th>\n",
       "      <td>1</td>\n",
       "      <td>1020 合庫</td>\n",
       "      <td>101.0</td>\n",
       "      <td>1,000</td>\n",
       "      <td>0</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>1</th>\n",
       "      <td>2</td>\n",
       "      <td>1021 合庫台中</td>\n",
       "      <td>101.0</td>\n",
       "      <td>0</td>\n",
       "      <td>2,000</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>2</th>\n",
       "      <td>3</td>\n",
       "      <td>102E 合庫桃園</td>\n",
       "      <td>101.5</td>\n",
       "      <td>1,000</td>\n",
       "      <td>0</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>3</th>\n",
       "      <td>4</td>\n",
       "      <td>102E 合庫桃園</td>\n",
       "      <td>102.5</td>\n",
       "      <td>6</td>\n",
       "      <td>5</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>4</th>\n",
       "      <td>5</td>\n",
       "      <td>1032 土銀台南</td>\n",
       "      <td>102.0</td>\n",
       "      <td>0</td>\n",
       "      <td>93</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>...</th>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>337</th>\n",
       "      <td>338</td>\n",
       "      <td>9B2Z 元富安南</td>\n",
       "      <td>103.0</td>\n",
       "      <td>0</td>\n",
       "      <td>300</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>338</th>\n",
       "      <td>339</td>\n",
       "      <td>9B2a 元富松德</td>\n",
       "      <td>101.5</td>\n",
       "      <td>0</td>\n",
       "      <td>1,745</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>339</th>\n",
       "      <td>340</td>\n",
       "      <td>9B2a 元富松德</td>\n",
       "      <td>102.0</td>\n",
       "      <td>0</td>\n",
       "      <td>1,643</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>340</th>\n",
       "      <td>341</td>\n",
       "      <td>9B2a 元富松德</td>\n",
       "      <td>102.5</td>\n",
       "      <td>0</td>\n",
       "      <td>570</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>341</th>\n",
       "      <td>342</td>\n",
       "      <td>9B2l 元富大裕</td>\n",
       "      <td>101.0</td>\n",
       "      <td>0</td>\n",
       "      <td>1,000</td>\n",
       "    </tr>\n",
       "  </tbody>\n",
       "</table>\n",
       "<p>342 rows × 5 columns</p>\n",
       "</div>"
      ],
      "text/plain": [
       "      序號         券商     價格   買進股數   賣出股數\n",
       "0      1    1020 合庫  101.0  1,000      0\n",
       "1      2  1021 合庫台中  101.0      0  2,000\n",
       "2      3  102E 合庫桃園  101.5  1,000      0\n",
       "3      4  102E 合庫桃園  102.5      6      5\n",
       "4      5  1032 土銀台南  102.0      0     93\n",
       "..   ...        ...    ...    ...    ...\n",
       "337  338  9B2Z 元富安南  103.0      0    300\n",
       "338  339  9B2a 元富松德  101.5      0  1,745\n",
       "339  340  9B2a 元富松德  102.0      0  1,643\n",
       "340  341  9B2a 元富松德  102.5      0    570\n",
       "341  342  9B2l 元富大裕  101.0      0  1,000\n",
       "\n",
       "[342 rows x 5 columns]"
      ]
     },
     "execution_count": 7,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "#將下載的檔案讀寫回檔案\n",
    "import io\n",
    "import pandas as pd\n",
    "time.sleep(10)\n",
    "file_path=f\"C:\\\\Users\\\\trista.huang\\\\Downloads\\\\5478_{date}.csv\"\n",
    "df = pd.read_csv(file_path, encoding='big5',header=2)\n",
    "df['買進股數'] = df['買進股數'].apply(lambda x: f\"{x:,}\") \n",
    "df['賣出股數'] = df['賣出股數'].apply(lambda x: f\"{x:,}\")\n",
    "df"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 8,
   "id": "ef4b85fc-4cc6-4867-9d06-931286bf53c8",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "智冠CSV 資料已成功讀取並寫入 Excel 第二分頁\n"
     ]
    }
   ],
   "source": [
    "wb_sw = xw.Book(target_path_sw)\n",
    "sheet_sw=wb_sw.sheets[1]\n",
    "\n",
    "sheet_sw.range('A3').value = [df.columns.tolist()] + df.values.tolist() \n",
    "print(\"智冠CSV 資料已成功讀取並寫入 Excel 第二分頁\")"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "f4a53f98-69f7-422f-a382-3128d4483ce1",
   "metadata": {},
   "source": [
    "CSV檔填入列表"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 9,
   "id": "5acf884e-824d-4cfe-8811-8b83eca1b78c",
   "metadata": {
    "scrolled": true
   },
   "outputs": [
    {
     "data": {
      "text/html": [
       "<div>\n",
       "<style scoped>\n",
       "    .dataframe tbody tr th:only-of-type {\n",
       "        vertical-align: middle;\n",
       "    }\n",
       "\n",
       "    .dataframe tbody tr th {\n",
       "        vertical-align: top;\n",
       "    }\n",
       "\n",
       "    .dataframe thead th {\n",
       "        text-align: right;\n",
       "    }\n",
       "</style>\n",
       "<table border=\"1\" class=\"dataframe\">\n",
       "  <thead>\n",
       "    <tr style=\"text-align: right;\">\n",
       "      <th></th>\n",
       "      <th>券商</th>\n",
       "      <th>加總-買進股數</th>\n",
       "      <th>加總-賣出股數</th>\n",
       "      <th>加總net</th>\n",
       "    </tr>\n",
       "  </thead>\n",
       "  <tbody>\n",
       "    <tr>\n",
       "      <th>0</th>\n",
       "      <td>1020 合庫</td>\n",
       "      <td>1000</td>\n",
       "      <td>0</td>\n",
       "      <td>1000</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>1</th>\n",
       "      <td>1021 合庫台中</td>\n",
       "      <td>0</td>\n",
       "      <td>2000</td>\n",
       "      <td>-2000</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>2</th>\n",
       "      <td>102E 合庫桃園</td>\n",
       "      <td>1006</td>\n",
       "      <td>5</td>\n",
       "      <td>1001</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>3</th>\n",
       "      <td>1032 土銀台南</td>\n",
       "      <td>0</td>\n",
       "      <td>93</td>\n",
       "      <td>-93</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>4</th>\n",
       "      <td>1038 土銀和平</td>\n",
       "      <td>1000</td>\n",
       "      <td>0</td>\n",
       "      <td>1000</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>...</th>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>220</th>\n",
       "      <td>9B2N 元富虎尾</td>\n",
       "      <td>1000</td>\n",
       "      <td>0</td>\n",
       "      <td>1000</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>221</th>\n",
       "      <td>9B2Z 元富安南</td>\n",
       "      <td>0</td>\n",
       "      <td>300</td>\n",
       "      <td>-300</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>222</th>\n",
       "      <td>9B2a 元富松德</td>\n",
       "      <td>0</td>\n",
       "      <td>3958</td>\n",
       "      <td>-3958</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>223</th>\n",
       "      <td>9B2l 元富大裕</td>\n",
       "      <td>0</td>\n",
       "      <td>1000</td>\n",
       "      <td>-1000</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>224</th>\n",
       "      <td>總計</td>\n",
       "      <td>265037</td>\n",
       "      <td>265037</td>\n",
       "      <td>0</td>\n",
       "    </tr>\n",
       "  </tbody>\n",
       "</table>\n",
       "<p>225 rows × 4 columns</p>\n",
       "</div>"
      ],
      "text/plain": [
       "            券商  加總-買進股數  加總-賣出股數  加總net\n",
       "0      1020 合庫     1000        0   1000\n",
       "1    1021 合庫台中        0     2000  -2000\n",
       "2    102E 合庫桃園     1006        5   1001\n",
       "3    1032 土銀台南        0       93    -93\n",
       "4    1038 土銀和平     1000        0   1000\n",
       "..         ...      ...      ...    ...\n",
       "220  9B2N 元富虎尾     1000        0   1000\n",
       "221  9B2Z 元富安南        0      300   -300\n",
       "222  9B2a 元富松德        0     3958  -3958\n",
       "223  9B2l 元富大裕        0     1000  -1000\n",
       "224         總計   265037   265037      0\n",
       "\n",
       "[225 rows x 4 columns]"
      ]
     },
     "execution_count": 9,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "#剔除序號和價格\n",
    "df= df.drop(columns=['序號', '價格'])\n",
    "#step 1 先改欄位名稱\n",
    "df = df.rename(columns={ \n",
    "    df.columns[1]: \"加總-買進股數\", \n",
    "    df.columns[2]: \"加總-賣出股數\",\n",
    "})\n",
    "#step 2 移除逗號\n",
    "df['加總-買進股數'] = df['加總-買進股數'].apply(lambda x: int(str(x).replace(',', '')))\n",
    "df['加總-賣出股數'] = df['加總-賣出股數'].apply(lambda x: int(str(x).replace(',', '')))\n",
    "\n",
    "# step 3先確保買進股數和賣出股數是int\n",
    "df['加總-買進股數'] =df['加總-買進股數'].astype(int)\n",
    "df['加總-賣出股數'] =df['加總-賣出股數'].astype(int)\n",
    "\n",
    "# step 4合併券商資料\n",
    "df= df.groupby('券商')[['加總-買進股數', '加總-賣出股數']].sum().reset_index()\n",
    "\n",
    "# step 5加入一行加總net\n",
    "df['加總net'] =df['加總-買進股數'] -df['加總-賣出股數']\n",
    "\n",
    "# step6 加入總計列\n",
    "summary_row = pd.DataFrame([{\n",
    "    '券商': '總計',\n",
    "    '加總-買進股數': df['加總-買進股數'].sum(),\n",
    "    '加總-賣出股數': df['加總-賣出股數'].sum(),\n",
    "    '加總net': df['加總net'].sum()\n",
    "}])\n",
    "df = pd.concat([df, summary_row], ignore_index=True)\n",
    "df"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "b9bd0b1a-85b6-46c5-ae64-bec7ecb6d3c0",
   "metadata": {},
   "outputs": [],
   "source": [
    "import os\n",
    "\n",
    "def apply_number_styles(filepath):\n",
    "    if not os.path.exists(filepath):\n",
    "        raise FileNotFoundError(f\"找不到檔案: {filepath}\")\n",
    "\n",
    "    app = xw.App(visible=False, add_book=False)\n",
    "    try:\n",
    "        wb = app.books.open(filepath)\n",
    "        ws = wb.sheets[0]  # 若要指定工作表請改成 wb.sheets['工作表名稱']\n",
    "        used = ws.used_range\n",
    "\n",
    "        # 取得 used_range 的起始列、起始行與列數、行數，逐格處理以避免 Range 迭代型態問題\n",
    "        start_row = 4\n",
    "        start_col = 1\n",
    "        rows = used.api.Rows.Count\n",
    "        cols = used.api.Columns.Count\n",
    "\n",
    "        for r in range(rows):\n",
    "            for c in range(cols):\n",
    "                cell = ws.range((start_row + r, start_col + c))\n",
    "                val = cell.value\n",
    "                # 排除非數字與布林\n",
    "                if isinstance(val, bool) or val is None:\n",
    "                    continue\n",
    "                if isinstance(val, (int, float)):\n",
    "                    # 判斷是否有小數位\n",
    "                    has_frac = isinstance(val, float) and not float(val).is_integer()\n",
    "                    if has_frac:\n",
    "                        # 正數；負數；零格式\n",
    "                        fmt = '#,##0.00;(#,##0.00);0.00'\n",
    "                    else:\n",
    "                        fmt = '#,##0;(#,##0);0'\n",
    "\n",
    "                    # 階段1：設定數字格式\n",
    "                    cell.number_format = fmt\n",
    "                    \n",
    "                    # 階段2：負數設定紅色字\n",
    "                    if val < 0:\n",
    "                        cell.font.color = 'FF0000'  # 紅色的十六進制碼\n",
    "        wb.save()\n",
    "   # finally:\n",
    "        #try:\n",
    "            #wb.close()\n",
    "        #except Exception:\n",
    "            #pass\n",
    "        #app.quit()\n",
    "\n",
    "if __name__ == '__main__':\n",
    "    # 請確認檔名與路徑正確\n",
    "    #filepath = (target_path_sw)\n",
    "    apply_number_styles(targer_path_sw)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 11,
   "id": "dba2fa07-9f23-4633-8943-6a128e541c82",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "列表資料已成功寫入\n"
     ]
    }
   ],
   "source": [
    "#sheet_sw=wb_sw.sheets[0]\n",
    "#sheet_sw.range('A3').options(index=False, header=True).value = df\n",
    "#print(\"列表資料已成功寫入\")"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "5739c475-73ab-4cdd-a427-c5da4fcca63c",
   "metadata": {},
   "source": [
    "STEP２　列出名單外資券商"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 12,
   "id": "b4958b05-2813-4f17-9d2c-953d0f16101f",
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/html": [
       "<div>\n",
       "<style scoped>\n",
       "    .dataframe tbody tr th:only-of-type {\n",
       "        vertical-align: middle;\n",
       "    }\n",
       "\n",
       "    .dataframe tbody tr th {\n",
       "        vertical-align: top;\n",
       "    }\n",
       "\n",
       "    .dataframe thead th {\n",
       "        text-align: right;\n",
       "    }\n",
       "</style>\n",
       "<table border=\"1\" class=\"dataframe\">\n",
       "  <thead>\n",
       "    <tr style=\"text-align: right;\">\n",
       "      <th></th>\n",
       "      <th>券商代號</th>\n",
       "      <th>券商名稱</th>\n",
       "      <th>加總-買進股數</th>\n",
       "      <th>加總-賣出股數</th>\n",
       "      <th>加總net</th>\n",
       "    </tr>\n",
       "  </thead>\n",
       "  <tbody>\n",
       "    <tr>\n",
       "      <th>0</th>\n",
       "      <td>1020</td>\n",
       "      <td>合庫</td>\n",
       "      <td>1000</td>\n",
       "      <td>0</td>\n",
       "      <td>1000</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>1</th>\n",
       "      <td>1021</td>\n",
       "      <td>合庫台中</td>\n",
       "      <td>0</td>\n",
       "      <td>2000</td>\n",
       "      <td>-2000</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>2</th>\n",
       "      <td>102E</td>\n",
       "      <td>合庫桃園</td>\n",
       "      <td>1006</td>\n",
       "      <td>5</td>\n",
       "      <td>1001</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>3</th>\n",
       "      <td>1032</td>\n",
       "      <td>土銀台南</td>\n",
       "      <td>0</td>\n",
       "      <td>93</td>\n",
       "      <td>-93</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>4</th>\n",
       "      <td>1038</td>\n",
       "      <td>土銀和平</td>\n",
       "      <td>1000</td>\n",
       "      <td>0</td>\n",
       "      <td>1000</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>...</th>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>220</th>\n",
       "      <td>9B2N</td>\n",
       "      <td>元富虎尾</td>\n",
       "      <td>1000</td>\n",
       "      <td>0</td>\n",
       "      <td>1000</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>221</th>\n",
       "      <td>9B2Z</td>\n",
       "      <td>元富安南</td>\n",
       "      <td>0</td>\n",
       "      <td>300</td>\n",
       "      <td>-300</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>222</th>\n",
       "      <td>9B2a</td>\n",
       "      <td>元富松德</td>\n",
       "      <td>0</td>\n",
       "      <td>3958</td>\n",
       "      <td>-3958</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>223</th>\n",
       "      <td>9B2l</td>\n",
       "      <td>元富大裕</td>\n",
       "      <td>0</td>\n",
       "      <td>1000</td>\n",
       "      <td>-1000</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>224</th>\n",
       "      <td>總計</td>\n",
       "      <td>None</td>\n",
       "      <td>265037</td>\n",
       "      <td>265037</td>\n",
       "      <td>0</td>\n",
       "    </tr>\n",
       "  </tbody>\n",
       "</table>\n",
       "<p>225 rows × 5 columns</p>\n",
       "</div>"
      ],
      "text/plain": [
       "     券商代號  券商名稱  加總-買進股數  加總-賣出股數  加總net\n",
       "0    1020    合庫     1000        0   1000\n",
       "1    1021  合庫台中        0     2000  -2000\n",
       "2    102E  合庫桃園     1006        5   1001\n",
       "3    1032  土銀台南        0       93    -93\n",
       "4    1038  土銀和平     1000        0   1000\n",
       "..    ...   ...      ...      ...    ...\n",
       "220  9B2N  元富虎尾     1000        0   1000\n",
       "221  9B2Z  元富安南        0      300   -300\n",
       "222  9B2a  元富松德        0     3958  -3958\n",
       "223  9B2l  元富大裕        0     1000  -1000\n",
       "224    總計  None   265037   265037      0\n",
       "\n",
       "[225 rows x 5 columns]"
      ]
     },
     "execution_count": 12,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "#將代號和券商名稱分開\n",
    "df[['券商代號', '券商名稱']] =df['券商'].str.split(' ',n=1, expand=True)\n",
    "# 重新排列欄位順序 \n",
    "df= df[['券商代號', '券商名稱', '加總-買進股數', '加總-賣出股數', '加總net']]\n",
    "df"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 13,
   "id": "4ea24d0d-e43d-4d60-803d-32cb1a89e480",
   "metadata": {},
   "outputs": [
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "C:\\Users\\trista.huang\\AppData\\Local\\Temp\\ipykernel_13744\\3890455092.py:2: SettingWithCopyWarning: \n",
      "A value is trying to be set on a copy of a slice from a DataFrame.\n",
      "Try using .loc[row_indexer,col_indexer] = value instead\n",
      "\n",
      "See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy\n",
      "  df['券商代號'] =df['券商代號'].astype(str)\n"
     ]
    },
    {
     "data": {
      "text/html": [
       "<div>\n",
       "<style scoped>\n",
       "    .dataframe tbody tr th:only-of-type {\n",
       "        vertical-align: middle;\n",
       "    }\n",
       "\n",
       "    .dataframe tbody tr th {\n",
       "        vertical-align: top;\n",
       "    }\n",
       "\n",
       "    .dataframe thead th {\n",
       "        text-align: right;\n",
       "    }\n",
       "</style>\n",
       "<table border=\"1\" class=\"dataframe\">\n",
       "  <thead>\n",
       "    <tr style=\"text-align: right;\">\n",
       "      <th></th>\n",
       "      <th>券商代號</th>\n",
       "      <th>券商名稱</th>\n",
       "      <th>加總-買進股數</th>\n",
       "      <th>加總-賣出股數</th>\n",
       "      <th>加總net</th>\n",
       "    </tr>\n",
       "  </thead>\n",
       "  <tbody>\n",
       "    <tr>\n",
       "      <th>12</th>\n",
       "      <td>1440</td>\n",
       "      <td>美林證券</td>\n",
       "      <td>55</td>\n",
       "      <td>0</td>\n",
       "      <td>55</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>13</th>\n",
       "      <td>1470</td>\n",
       "      <td>摩根士丹利</td>\n",
       "      <td>1000</td>\n",
       "      <td>8000</td>\n",
       "      <td>-7000</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>14</th>\n",
       "      <td>1480</td>\n",
       "      <td>美商高盛亞</td>\n",
       "      <td>8000</td>\n",
       "      <td>5000</td>\n",
       "      <td>3000</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>15</th>\n",
       "      <td>1560</td>\n",
       "      <td>港商野村</td>\n",
       "      <td>0</td>\n",
       "      <td>3000</td>\n",
       "      <td>-3000</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>16</th>\n",
       "      <td>1650</td>\n",
       "      <td>星洲瑞銀</td>\n",
       "      <td>3000</td>\n",
       "      <td>4000</td>\n",
       "      <td>-1000</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>65</th>\n",
       "      <td>8440</td>\n",
       "      <td>摩根大通</td>\n",
       "      <td>4000</td>\n",
       "      <td>20000</td>\n",
       "      <td>-16000</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>112</th>\n",
       "      <td>9268</td>\n",
       "      <td>凱基台北</td>\n",
       "      <td>12004</td>\n",
       "      <td>35000</td>\n",
       "      <td>-22996</td>\n",
       "    </tr>\n",
       "  </tbody>\n",
       "</table>\n",
       "</div>"
      ],
      "text/plain": [
       "     券商代號   券商名稱  加總-買進股數  加總-賣出股數  加總net\n",
       "12   1440   美林證券       55        0     55\n",
       "13   1470  摩根士丹利     1000     8000  -7000\n",
       "14   1480  美商高盛亞     8000     5000   3000\n",
       "15   1560   港商野村        0     3000  -3000\n",
       "16   1650   星洲瑞銀     3000     4000  -1000\n",
       "65   8440   摩根大通     4000    20000 -16000\n",
       "112  9268   凱基台北    12004    35000 -22996"
      ]
     },
     "execution_count": 13,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "#先確保券商代號是字串再篩選\n",
    "df['券商代號'] =df['券商代號'].astype(str)\n",
    "target_ids = ['1360', '1380', '1440', '1470', '1480', '1520', '1530', '1560','1570', '1590', '1650','8440', '8890', '8900', '8910', '8960','9268']\n",
    "filtered = df[df['券商代號'].isin(target_ids)]\n",
    "filtered"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 14,
   "id": "29e2c2de-05c8-4575-a2f0-2eefb75fb834",
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/html": [
       "<div>\n",
       "<style scoped>\n",
       "    .dataframe tbody tr th:only-of-type {\n",
       "        vertical-align: middle;\n",
       "    }\n",
       "\n",
       "    .dataframe tbody tr th {\n",
       "        vertical-align: top;\n",
       "    }\n",
       "\n",
       "    .dataframe thead th {\n",
       "        text-align: right;\n",
       "    }\n",
       "</style>\n",
       "<table border=\"1\" class=\"dataframe\">\n",
       "  <thead>\n",
       "    <tr style=\"text-align: right;\">\n",
       "      <th></th>\n",
       "      <th>券商代號</th>\n",
       "      <th>券商名稱</th>\n",
       "      <th>單日增(減)變動</th>\n",
       "    </tr>\n",
       "  </thead>\n",
       "  <tbody>\n",
       "    <tr>\n",
       "      <th>0</th>\n",
       "      <td>1440</td>\n",
       "      <td>美林證券</td>\n",
       "      <td>55</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>1</th>\n",
       "      <td>1470</td>\n",
       "      <td>摩根士丹利</td>\n",
       "      <td>-7000</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>2</th>\n",
       "      <td>1480</td>\n",
       "      <td>美商高盛亞</td>\n",
       "      <td>3000</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>3</th>\n",
       "      <td>1560</td>\n",
       "      <td>港商野村</td>\n",
       "      <td>-3000</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>4</th>\n",
       "      <td>1650</td>\n",
       "      <td>星洲瑞銀</td>\n",
       "      <td>-1000</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>5</th>\n",
       "      <td>8440</td>\n",
       "      <td>摩根大通</td>\n",
       "      <td>-16000</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>6</th>\n",
       "      <td>9268</td>\n",
       "      <td>凱基台北</td>\n",
       "      <td>-22996</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>7</th>\n",
       "      <td></td>\n",
       "      <td>外資買賣超合計</td>\n",
       "      <td>-46941</td>\n",
       "    </tr>\n",
       "  </tbody>\n",
       "</table>\n",
       "</div>"
      ],
      "text/plain": [
       "   券商代號     券商名稱  單日增(減)變動\n",
       "0  1440     美林證券        55\n",
       "1  1470    摩根士丹利     -7000\n",
       "2  1480    美商高盛亞      3000\n",
       "3  1560     港商野村     -3000\n",
       "4  1650     星洲瑞銀     -1000\n",
       "5  8440     摩根大通    -16000\n",
       "6  9268     凱基台北    -22996\n",
       "7        外資買賣超合計    -46941"
      ]
     },
     "execution_count": 14,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "#只留下券商代號、券商名稱和加總net\n",
    "filtered= filtered.drop(columns=['加總-買進股數', '加總-賣出股數'])\n",
    "#把加總Net更名\n",
    "filtered= filtered.rename(columns={\"加總net\": \"單日增(減)變動\"})\n",
    "#計算總和\n",
    "total_net = filtered['單日增(減)變動'].sum()\n",
    "# 建立一列總和資料 \n",
    "summary_row = pd.DataFrame([{ \n",
    "    '券商代號': '', \n",
    "    '券商名稱': '外資買賣超合計', \n",
    "    '單日增(減)變動': int(total_net)\n",
    "}])\n",
    "# 合併到原表格底部 \n",
    "filtered= pd.concat([filtered, summary_row], ignore_index=True)\n",
    "\n",
    "\n",
    "filtered"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 15,
   "id": "f270fc4e-59d4-4448-bc90-25b470911c48",
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/html": [
       "<div>\n",
       "<style scoped>\n",
       "    .dataframe tbody tr th:only-of-type {\n",
       "        vertical-align: middle;\n",
       "    }\n",
       "\n",
       "    .dataframe tbody tr th {\n",
       "        vertical-align: top;\n",
       "    }\n",
       "\n",
       "    .dataframe thead th {\n",
       "        text-align: right;\n",
       "    }\n",
       "</style>\n",
       "<table border=\"1\" class=\"dataframe\">\n",
       "  <thead>\n",
       "    <tr style=\"text-align: right;\">\n",
       "      <th></th>\n",
       "      <th>券商代號</th>\n",
       "      <th>券商名稱</th>\n",
       "      <th>單日增(減)變動</th>\n",
       "    </tr>\n",
       "  </thead>\n",
       "  <tbody>\n",
       "    <tr>\n",
       "      <th>0</th>\n",
       "      <td>1440</td>\n",
       "      <td>美林證券</td>\n",
       "      <td>55</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>1</th>\n",
       "      <td>1470</td>\n",
       "      <td>摩根士丹利</td>\n",
       "      <td>-7000</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>2</th>\n",
       "      <td>1480</td>\n",
       "      <td>美商高盛亞</td>\n",
       "      <td>3000</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>3</th>\n",
       "      <td>1560</td>\n",
       "      <td>港商野村</td>\n",
       "      <td>-3000</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>4</th>\n",
       "      <td>1650</td>\n",
       "      <td>星洲瑞銀</td>\n",
       "      <td>-1000</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>5</th>\n",
       "      <td>8440</td>\n",
       "      <td>摩根大通</td>\n",
       "      <td>-16000</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>6</th>\n",
       "      <td>9268</td>\n",
       "      <td>凱基台北</td>\n",
       "      <td>-22996</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>7</th>\n",
       "      <td></td>\n",
       "      <td>外資買賣超合計</td>\n",
       "      <td>-46941</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>8</th>\n",
       "      <td></td>\n",
       "      <td>DIFF</td>\n",
       "      <td></td>\n",
       "    </tr>\n",
       "  </tbody>\n",
       "</table>\n",
       "</div>"
      ],
      "text/plain": [
       "   券商代號     券商名稱 單日增(減)變動\n",
       "0  1440     美林證券       55\n",
       "1  1470    摩根士丹利    -7000\n",
       "2  1480    美商高盛亞     3000\n",
       "3  1560     港商野村    -3000\n",
       "4  1650     星洲瑞銀    -1000\n",
       "5  8440     摩根大通   -16000\n",
       "6  9268     凱基台北   -22996\n",
       "7        外資買賣超合計   -46941\n",
       "8           DIFF         "
      ]
     },
     "execution_count": 15,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "# 建立一列空白 diff 欄位\n",
    "diff_row = pd.DataFrame([{ \n",
    "    '券商代號': '', \n",
    "    '券商名稱': 'DIFF', \n",
    "    '單日增(減)變動': '', \n",
    "}])\n",
    "filtered2=pd.concat([filtered, diff_row], ignore_index=True)\n",
    "filtered2"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 16,
   "id": "d73eb052-b6b7-4ee3-856c-87221329bcb0",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "-54000\n"
     ]
    }
   ],
   "source": [
    "#先爬取外資合計買賣超\n",
    "from selenium.webdriver.support.ui import WebDriverWait\n",
    "from selenium.webdriver.support import expected_conditions as EC\n",
    "\n",
    "options = uc.ChromeOptions()\n",
    "options.add_argument(\"--disable-blink-features=AutomationControlled\")\n",
    "driver = uc.Chrome(version_main=144, options=options)\n",
    "\n",
    "url = f\"https://justdata.moneydj.com/z/zc/zcl/zcl.djhtm?a=5478&c={now.year}-{now.month}-{now.day}&d={now.year}-{now.month}-{now.day:02d}\"\n",
    "driver.get(url)\n",
    "\n",
    "body = WebDriverWait(driver, 10).until(\n",
    "       EC.presence_of_element_located((By.XPATH, \"//td[@class='t3r1']\"))\n",
    ")\n",
    "value = (int(body.text))*1000\n",
    "print(value)\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 17,
   "id": "2f222784-26ed-4181-b8f0-afcd23728d50",
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/html": [
       "<div>\n",
       "<style scoped>\n",
       "    .dataframe tbody tr th:only-of-type {\n",
       "        vertical-align: middle;\n",
       "    }\n",
       "\n",
       "    .dataframe tbody tr th {\n",
       "        vertical-align: top;\n",
       "    }\n",
       "\n",
       "    .dataframe thead th {\n",
       "        text-align: right;\n",
       "    }\n",
       "</style>\n",
       "<table border=\"1\" class=\"dataframe\">\n",
       "  <thead>\n",
       "    <tr style=\"text-align: right;\">\n",
       "      <th></th>\n",
       "      <th>券商代號</th>\n",
       "      <th>券商名稱</th>\n",
       "      <th>單日增(減)變動</th>\n",
       "    </tr>\n",
       "  </thead>\n",
       "  <tbody>\n",
       "    <tr>\n",
       "      <th>0</th>\n",
       "      <td>1440</td>\n",
       "      <td>美林證券</td>\n",
       "      <td>55</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>1</th>\n",
       "      <td>1470</td>\n",
       "      <td>摩根士丹利</td>\n",
       "      <td>-7000</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>2</th>\n",
       "      <td>1480</td>\n",
       "      <td>美商高盛亞</td>\n",
       "      <td>3000</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>3</th>\n",
       "      <td>1560</td>\n",
       "      <td>港商野村</td>\n",
       "      <td>-3000</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>4</th>\n",
       "      <td>1650</td>\n",
       "      <td>星洲瑞銀</td>\n",
       "      <td>-1000</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>5</th>\n",
       "      <td>8440</td>\n",
       "      <td>摩根大通</td>\n",
       "      <td>-16000</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>6</th>\n",
       "      <td>9268</td>\n",
       "      <td>凱基台北</td>\n",
       "      <td>-22996</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>7</th>\n",
       "      <td></td>\n",
       "      <td>外資買賣超合計</td>\n",
       "      <td>-46941</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>8</th>\n",
       "      <td></td>\n",
       "      <td>DIFF</td>\n",
       "      <td></td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>9</th>\n",
       "      <td></td>\n",
       "      <td>外資券商買賣超小計</td>\n",
       "      <td>-54000</td>\n",
       "    </tr>\n",
       "  </tbody>\n",
       "</table>\n",
       "</div>"
      ],
      "text/plain": [
       "   券商代號       券商名稱 單日增(減)變動\n",
       "0  1440       美林證券       55\n",
       "1  1470      摩根士丹利    -7000\n",
       "2  1480      美商高盛亞     3000\n",
       "3  1560       港商野村    -3000\n",
       "4  1650       星洲瑞銀    -1000\n",
       "5  8440       摩根大通   -16000\n",
       "6  9268       凱基台北   -22996\n",
       "7          外資買賣超合計   -46941\n",
       "8             DIFF         \n",
       "9        外資券商買賣超小計   -54000"
      ]
     },
     "execution_count": 17,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "#建立一列外資卷商買賣超小計\n",
    "all_stocker_net=pd.DataFrame([{ \n",
    "    '券商代號': '', \n",
    "    '券商名稱': '外資券商買賣超小計', \n",
    "    '單日增(減)變動': f\"{value}\", \n",
    "}])\n",
    "filtered3=pd.concat([filtered2,all_stocker_net], ignore_index=True)\n",
    "filtered3"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 18,
   "id": "a9b4666a-85df-4062-b282-d7792ef2d1de",
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/html": [
       "<div>\n",
       "<style scoped>\n",
       "    .dataframe tbody tr th:only-of-type {\n",
       "        vertical-align: middle;\n",
       "    }\n",
       "\n",
       "    .dataframe tbody tr th {\n",
       "        vertical-align: top;\n",
       "    }\n",
       "\n",
       "    .dataframe thead th {\n",
       "        text-align: right;\n",
       "    }\n",
       "</style>\n",
       "<table border=\"1\" class=\"dataframe\">\n",
       "  <thead>\n",
       "    <tr style=\"text-align: right;\">\n",
       "      <th></th>\n",
       "      <th>券商代號</th>\n",
       "      <th>券商名稱</th>\n",
       "      <th>單日增(減)變動</th>\n",
       "    </tr>\n",
       "  </thead>\n",
       "  <tbody>\n",
       "    <tr>\n",
       "      <th>0</th>\n",
       "      <td>1440</td>\n",
       "      <td>美林證券</td>\n",
       "      <td>55</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>1</th>\n",
       "      <td>1470</td>\n",
       "      <td>摩根士丹利</td>\n",
       "      <td>-7000</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>2</th>\n",
       "      <td>1480</td>\n",
       "      <td>美商高盛亞</td>\n",
       "      <td>3000</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>3</th>\n",
       "      <td>1560</td>\n",
       "      <td>港商野村</td>\n",
       "      <td>-3000</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>4</th>\n",
       "      <td>1650</td>\n",
       "      <td>星洲瑞銀</td>\n",
       "      <td>-1000</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>5</th>\n",
       "      <td>8440</td>\n",
       "      <td>摩根大通</td>\n",
       "      <td>-16000</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>6</th>\n",
       "      <td>9268</td>\n",
       "      <td>凱基台北</td>\n",
       "      <td>-22996</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>7</th>\n",
       "      <td></td>\n",
       "      <td>外資買賣超合計</td>\n",
       "      <td>-46941</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>8</th>\n",
       "      <td></td>\n",
       "      <td>DIFF</td>\n",
       "      <td>7059</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>9</th>\n",
       "      <td></td>\n",
       "      <td>外資券商買賣超小計</td>\n",
       "      <td>-54000</td>\n",
       "    </tr>\n",
       "  </tbody>\n",
       "</table>\n",
       "</div>"
      ],
      "text/plain": [
       "   券商代號       券商名稱  單日增(減)變動\n",
       "0  1440       美林證券        55\n",
       "1  1470      摩根士丹利     -7000\n",
       "2  1480      美商高盛亞      3000\n",
       "3  1560       港商野村     -3000\n",
       "4  1650       星洲瑞銀     -1000\n",
       "5  8440       摩根大通    -16000\n",
       "6  9268       凱基台北    -22996\n",
       "7          外資買賣超合計    -46941\n",
       "8             DIFF      7059\n",
       "9        外資券商買賣超小計    -54000"
      ]
     },
     "execution_count": 18,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "import pandas as pd\n",
    "import numpy as np\n",
    "# 先把「單日增(減)變動」欄位轉成數字，非數字的轉成 NaN\n",
    "filtered3[\"單日增(減)變動\"] = pd.to_numeric(filtered3[\"單日增(減)變動\"], errors=\"coerce\")\n",
    "\n",
    "# 找出「總和」和「外資券商買賣超小計」的值\n",
    "total_net = filtered3.loc[filtered3[\"券商名稱\"] == \"外資買賣超合計\", \"單日增(減)變動\"].values[0]\n",
    "subtotal = filtered3.loc[filtered3[\"券商名稱\"] == \"外資券商買賣超小計\", \"單日增(減)變動\"].values[0]\n",
    "\n",
    "# 計算 diff\n",
    "diff_value = total_net - subtotal\n",
    "\n",
    "# 更新 DataFrame 的 diff 列\n",
    "filtered3.loc[filtered3[\"券商名稱\"] == \"DIFF\", \"單日增(減)變動\"] = diff_value\n",
    "filtered3[\"單日增(減)變動\"] = filtered3[\"單日增(減)變動\"].astype(int)\n",
    "\n",
    "filtered3"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 19,
   "id": "57168740-a640-4c63-a90a-3f7481878775",
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/html": [
       "<style type=\"text/css\">\n",
       "</style>\n",
       "<table id=\"T_83af7\">\n",
       "  <thead>\n",
       "    <tr>\n",
       "      <th class=\"blank level0\" >&nbsp;</th>\n",
       "      <th id=\"T_83af7_level0_col0\" class=\"col_heading level0 col0\" >券商代號</th>\n",
       "      <th id=\"T_83af7_level0_col1\" class=\"col_heading level0 col1\" >券商名稱</th>\n",
       "      <th id=\"T_83af7_level0_col2\" class=\"col_heading level0 col2\" >單日增(減)變動</th>\n",
       "    </tr>\n",
       "  </thead>\n",
       "  <tbody>\n",
       "    <tr>\n",
       "      <th id=\"T_83af7_level0_row0\" class=\"row_heading level0 row0\" >0</th>\n",
       "      <td id=\"T_83af7_row0_col0\" class=\"data row0 col0\" >1440</td>\n",
       "      <td id=\"T_83af7_row0_col1\" class=\"data row0 col1\" >美林證券</td>\n",
       "      <td id=\"T_83af7_row0_col2\" class=\"data row0 col2\" >55</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th id=\"T_83af7_level0_row1\" class=\"row_heading level0 row1\" >1</th>\n",
       "      <td id=\"T_83af7_row1_col0\" class=\"data row1 col0\" >1470</td>\n",
       "      <td id=\"T_83af7_row1_col1\" class=\"data row1 col1\" >摩根士丹利</td>\n",
       "      <td id=\"T_83af7_row1_col2\" class=\"data row1 col2\" ><span style='color:red'>(7,000)</span></td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th id=\"T_83af7_level0_row2\" class=\"row_heading level0 row2\" >2</th>\n",
       "      <td id=\"T_83af7_row2_col0\" class=\"data row2 col0\" >1480</td>\n",
       "      <td id=\"T_83af7_row2_col1\" class=\"data row2 col1\" >美商高盛亞</td>\n",
       "      <td id=\"T_83af7_row2_col2\" class=\"data row2 col2\" >3,000</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th id=\"T_83af7_level0_row3\" class=\"row_heading level0 row3\" >3</th>\n",
       "      <td id=\"T_83af7_row3_col0\" class=\"data row3 col0\" >1560</td>\n",
       "      <td id=\"T_83af7_row3_col1\" class=\"data row3 col1\" >港商野村</td>\n",
       "      <td id=\"T_83af7_row3_col2\" class=\"data row3 col2\" ><span style='color:red'>(3,000)</span></td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th id=\"T_83af7_level0_row4\" class=\"row_heading level0 row4\" >4</th>\n",
       "      <td id=\"T_83af7_row4_col0\" class=\"data row4 col0\" >1650</td>\n",
       "      <td id=\"T_83af7_row4_col1\" class=\"data row4 col1\" >星洲瑞銀</td>\n",
       "      <td id=\"T_83af7_row4_col2\" class=\"data row4 col2\" ><span style='color:red'>(1,000)</span></td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th id=\"T_83af7_level0_row5\" class=\"row_heading level0 row5\" >5</th>\n",
       "      <td id=\"T_83af7_row5_col0\" class=\"data row5 col0\" >8440</td>\n",
       "      <td id=\"T_83af7_row5_col1\" class=\"data row5 col1\" >摩根大通</td>\n",
       "      <td id=\"T_83af7_row5_col2\" class=\"data row5 col2\" ><span style='color:red'>(16,000)</span></td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th id=\"T_83af7_level0_row6\" class=\"row_heading level0 row6\" >6</th>\n",
       "      <td id=\"T_83af7_row6_col0\" class=\"data row6 col0\" >9268</td>\n",
       "      <td id=\"T_83af7_row6_col1\" class=\"data row6 col1\" >凱基台北</td>\n",
       "      <td id=\"T_83af7_row6_col2\" class=\"data row6 col2\" ><span style='color:red'>(22,996)</span></td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th id=\"T_83af7_level0_row7\" class=\"row_heading level0 row7\" >7</th>\n",
       "      <td id=\"T_83af7_row7_col0\" class=\"data row7 col0\" ></td>\n",
       "      <td id=\"T_83af7_row7_col1\" class=\"data row7 col1\" >外資買賣超合計</td>\n",
       "      <td id=\"T_83af7_row7_col2\" class=\"data row7 col2\" ><span style='color:red'>(46,941)</span></td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th id=\"T_83af7_level0_row8\" class=\"row_heading level0 row8\" >8</th>\n",
       "      <td id=\"T_83af7_row8_col0\" class=\"data row8 col0\" ></td>\n",
       "      <td id=\"T_83af7_row8_col1\" class=\"data row8 col1\" >DIFF</td>\n",
       "      <td id=\"T_83af7_row8_col2\" class=\"data row8 col2\" >7,059</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th id=\"T_83af7_level0_row9\" class=\"row_heading level0 row9\" >9</th>\n",
       "      <td id=\"T_83af7_row9_col0\" class=\"data row9 col0\" ></td>\n",
       "      <td id=\"T_83af7_row9_col1\" class=\"data row9 col1\" >外資券商買賣超小計</td>\n",
       "      <td id=\"T_83af7_row9_col2\" class=\"data row9 col2\" ><span style='color:red'>(54,000)</span></td>\n",
       "    </tr>\n",
       "  </tbody>\n",
       "</table>\n"
      ],
      "text/plain": [
       "<pandas.io.formats.style.Styler at 0x2c30bab9e80>"
      ]
     },
     "execution_count": 19,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "def format_negative(val):\n",
    "    if val < 0:\n",
    "        return f\"<span style='color:red'>({abs(val):,})</span>\"\n",
    "    else:\n",
    "        return f\"{val:,}\"\n",
    "\n",
    "# 不要覆蓋原本的 DataFrame，直接建立一個 Styler 物件\n",
    "styled = filtered3.style.format({'單日增(減)變動': format_negative})\n",
    "styled\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 20,
   "id": "40123bfe-60c7-4dc9-a005-ccf3c3ae3782",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "外資券商資料已成功寫入\n"
     ]
    }
   ],
   "source": [
    "sheet_sw=wb_sw.sheets[0]\n",
    "sheet_sw.range('F13').options(index=False, header=True).value = filtered3\n",
    "print(\"外資券商資料已成功寫入\")"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "cd9bf0ba-59aa-40ea-b39e-3015478fdf6f",
   "metadata": {},
   "source": [
    "Step3 列出關注分點名單"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 21,
   "id": "04f1bb49-c1f3-4166-95df-2b275f41b7bc",
   "metadata": {},
   "outputs": [
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "C:\\Users\\trista.huang\\AppData\\Local\\Temp\\ipykernel_13744\\3651088646.py:5: SettingWithCopyWarning: \n",
      "A value is trying to be set on a copy of a slice from a DataFrame.\n",
      "Try using .loc[row_indexer,col_indexer] = value instead\n",
      "\n",
      "See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy\n",
      "  list['加總-買進股數'] =list['加總-買進股數'].replace(',', '', regex=True).astype(int)\n",
      "C:\\Users\\trista.huang\\AppData\\Local\\Temp\\ipykernel_13744\\3651088646.py:6: SettingWithCopyWarning: \n",
      "A value is trying to be set on a copy of a slice from a DataFrame.\n",
      "Try using .loc[row_indexer,col_indexer] = value instead\n",
      "\n",
      "See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy\n",
      "  list['加總-賣出股數'] =list['加總-賣出股數'].replace(',', '', regex=True).astype(int)\n",
      "C:\\Users\\trista.huang\\AppData\\Local\\Temp\\ipykernel_13744\\3651088646.py:7: SettingWithCopyWarning: \n",
      "A value is trying to be set on a copy of a slice from a DataFrame.\n",
      "Try using .loc[row_indexer,col_indexer] = value instead\n",
      "\n",
      "See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy\n",
      "  list['加總net'] =list['加總net'].replace(',', '', regex=True).astype(int)\n"
     ]
    },
    {
     "data": {
      "text/html": [
       "<div>\n",
       "<style scoped>\n",
       "    .dataframe tbody tr th:only-of-type {\n",
       "        vertical-align: middle;\n",
       "    }\n",
       "\n",
       "    .dataframe tbody tr th {\n",
       "        vertical-align: top;\n",
       "    }\n",
       "\n",
       "    .dataframe thead th {\n",
       "        text-align: right;\n",
       "    }\n",
       "</style>\n",
       "<table border=\"1\" class=\"dataframe\">\n",
       "  <thead>\n",
       "    <tr style=\"text-align: right;\">\n",
       "      <th></th>\n",
       "      <th>券商代號</th>\n",
       "      <th>券商名稱</th>\n",
       "      <th>加總-買進股數</th>\n",
       "      <th>加總-賣出股數</th>\n",
       "      <th>加總net</th>\n",
       "    </tr>\n",
       "  </thead>\n",
       "  <tbody>\n",
       "    <tr>\n",
       "      <th>0</th>\n",
       "      <td>700G</td>\n",
       "      <td>兆豐麻豆</td>\n",
       "      <td>54</td>\n",
       "      <td>0</td>\n",
       "      <td>54</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>1</th>\n",
       "      <td>884J</td>\n",
       "      <td>玉山大里</td>\n",
       "      <td>1,000</td>\n",
       "      <td>0</td>\n",
       "      <td>1,000</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>2</th>\n",
       "      <td>8888</td>\n",
       "      <td>國泰敦南</td>\n",
       "      <td>5,373</td>\n",
       "      <td>1,079</td>\n",
       "      <td>4,294</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>3</th>\n",
       "      <td>965K</td>\n",
       "      <td>富邦台中</td>\n",
       "      <td>1,000</td>\n",
       "      <td>2,000</td>\n",
       "      <td>-1000</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>4</th>\n",
       "      <td></td>\n",
       "      <td>分點合計</td>\n",
       "      <td>7,427</td>\n",
       "      <td>3,079</td>\n",
       "      <td>4,348</td>\n",
       "    </tr>\n",
       "  </tbody>\n",
       "</table>\n",
       "</div>"
      ],
      "text/plain": [
       "   券商代號  券商名稱 加總-買進股數 加總-賣出股數  加總net\n",
       "0  700G  兆豐麻豆      54       0     54\n",
       "1  884J  玉山大里   1,000       0  1,000\n",
       "2  8888  國泰敦南   5,373   1,079  4,294\n",
       "3  965K  富邦台中   1,000   2,000  -1000\n",
       "4        分點合計   7,427   3,079  4,348"
      ]
     },
     "execution_count": 21,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "#列出關注分點名單\n",
    "target_ids2 = ['884J', '9811', '700G', '9666', '8843', '965K', '8888', '538P','9A9L']\n",
    "list= df[df['券商代號'].isin(target_ids2)]\n",
    "#把各股數轉換成int\n",
    "list['加總-買進股數'] =list['加總-買進股數'].replace(',', '', regex=True).astype(int)\n",
    "list['加總-賣出股數'] =list['加總-賣出股數'].replace(',', '', regex=True).astype(int)\n",
    "list['加總net'] =list['加總net'].replace(',', '', regex=True).astype(int)\n",
    "\n",
    "#計算總和\n",
    "total_buy = list['加總-買進股數'].sum()\n",
    "total_sale = list['加總-賣出股數'].sum()\n",
    "total_net = list['加總net'].sum()\n",
    "#加入加總欄位\n",
    "all_list_net=pd.DataFrame([{ \n",
    "    '券商代號': '',\n",
    "    '券商名稱': '分點合計', \n",
    "    '加總-買進股數':f\"{total_buy}\",\n",
    "    '加總-賣出股數':f\"{total_sale}\",\n",
    "    '加總net':f\"{total_net}\", \n",
    "}])\n",
    "list=pd.concat([list,all_list_net], ignore_index=True)\n",
    "\n",
    "for col in ['加總-買進股數', '加總-賣出股數', '加總net']:\n",
    "    list[col] = list[col].apply(lambda x: f\"{int(x):,}\" if str(x).replace(',', '').isdigit() else x)\n",
    "list"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 22,
   "id": "74f6bd4a-ab3a-416e-bcfc-fe7e79f8a064",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "回寫完成\n"
     ]
    }
   ],
   "source": [
    "sheet_sw=wb_sw.sheets[0]\n",
    "sheet_sw.range('J13').options(index=False, header=True).value = list\n",
    "print(\"回寫完成\")"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "9e339a19-1da0-44df-bb24-cf53d1dd2ce5",
   "metadata": {},
   "source": [
    "STEP4 法人持股明細爬取，寫回檔案"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 23,
   "id": "284c0f9f-4c55-4c97-a472-63d11cabf72c",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "表格數量: 4\n"
     ]
    }
   ],
   "source": [
    "#法人持股明細\n",
    "import io\n",
    "import requests\n",
    "import pandas as pd\n",
    "import requests.packages.urllib3\n",
    "requests.packages.urllib3.disable_warnings()\n",
    "\n",
    "\n",
    "def fetch_get(url, encoding=\"big5\"):\n",
    "    try:\n",
    "        r = requests.get(url, verify=False)\n",
    "        r.raise_for_status()          \n",
    "    except Exception as e:\n",
    "        print(f\"錯誤訊息：{e}\")\n",
    "        return None\n",
    "    else:\n",
    "        r.encoding = encoding\n",
    "        return r.text\n",
    "\n",
    "url=f\"https://justdata.moneydj.com/z/zc/zcl/zcl.djhtm?a=5478&c={now.year}-{now.month}-{now.day}&d={now.year}-{now.month}-{now.day:02d}\"\n",
    "data = fetch_get(url)\n",
    "    \n",
    "try:\n",
    "    dfs = pd.read_html(io.StringIO(data))\n",
    "    # dfs = pd.read_html(\"b04b-每日收盤行情.html\")   # 網路爬取有問題時的備用檔\n",
    "except Exception as e:\n",
    "    print(f\"錯誤訊息：{e}\")\n",
    "else:\n",
    "    print(f\"表格數量: {len(dfs)}\")"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 24,
   "id": "c41c0cfe-d607-460d-bc4c-3ebddf56623e",
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/html": [
       "<div>\n",
       "<style scoped>\n",
       "    .dataframe tbody tr th:only-of-type {\n",
       "        vertical-align: middle;\n",
       "    }\n",
       "\n",
       "    .dataframe tbody tr th {\n",
       "        vertical-align: top;\n",
       "    }\n",
       "\n",
       "    .dataframe thead th {\n",
       "        text-align: right;\n",
       "    }\n",
       "</style>\n",
       "<table border=\"1\" class=\"dataframe\">\n",
       "  <thead>\n",
       "    <tr style=\"text-align: right;\">\n",
       "      <th></th>\n",
       "      <th>0</th>\n",
       "      <th>1</th>\n",
       "      <th>2</th>\n",
       "      <th>3</th>\n",
       "      <th>4</th>\n",
       "      <th>5</th>\n",
       "      <th>6</th>\n",
       "      <th>7</th>\n",
       "      <th>8</th>\n",
       "      <th>9</th>\n",
       "      <th>10</th>\n",
       "    </tr>\n",
       "  </thead>\n",
       "  <tbody>\n",
       "    <tr>\n",
       "      <th>0</th>\n",
       "      <td>智冠(5478)法人持股走勢圖</td>\n",
       "      <td>智冠(5478)法人持股走勢圖</td>\n",
       "      <td>智冠(5478)法人持股走勢圖</td>\n",
       "      <td>智冠(5478)法人持股走勢圖</td>\n",
       "      <td>智冠(5478)法人持股走勢圖</td>\n",
       "      <td>智冠(5478)法人持股走勢圖</td>\n",
       "      <td>智冠(5478)法人持股走勢圖</td>\n",
       "      <td>智冠(5478)法人持股走勢圖</td>\n",
       "      <td>智冠(5478)法人持股走勢圖</td>\n",
       "      <td>智冠(5478)法人持股走勢圖</td>\n",
       "      <td>智冠(5478)法人持股走勢圖</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>1</th>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>2</th>\n",
       "      <td>智冠(5478)法人持股明細</td>\n",
       "      <td>智冠(5478)法人持股明細</td>\n",
       "      <td>智冠(5478)法人持股明細</td>\n",
       "      <td>智冠(5478)法人持股明細</td>\n",
       "      <td>智冠(5478)法人持股明細</td>\n",
       "      <td>智冠(5478)法人持股明細</td>\n",
       "      <td>智冠(5478)法人持股明細</td>\n",
       "      <td>智冠(5478)法人持股明細</td>\n",
       "      <td>智冠(5478)法人持股明細</td>\n",
       "      <td>智冠(5478)法人持股明細</td>\n",
       "      <td>智冠(5478)法人持股明細</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>3</th>\n",
       "      <td>請選擇 近五日 近十日 近20日 近40日  自設區間： 從 年 月 日 ∼ 年 月 日 &lt;...</td>\n",
       "      <td>請選擇 近五日 近十日 近20日 近40日  自設區間： 從 年 月 日 ∼ 年 月 日 &lt;...</td>\n",
       "      <td>請選擇 近五日 近十日 近20日 近40日  自設區間： 從 年 月 日 ∼ 年 月 日 &lt;...</td>\n",
       "      <td>請選擇 近五日 近十日 近20日 近40日  自設區間： 從 年 月 日 ∼ 年 月 日 &lt;...</td>\n",
       "      <td>請選擇 近五日 近十日 近20日 近40日  自設區間： 從 年 月 日 ∼ 年 月 日 &lt;...</td>\n",
       "      <td>請選擇 近五日 近十日 近20日 近40日  自設區間： 從 年 月 日 ∼ 年 月 日 &lt;...</td>\n",
       "      <td>請選擇 近五日 近十日 近20日 近40日  自設區間： 從 年 月 日 ∼ 年 月 日 &lt;...</td>\n",
       "      <td>請選擇 近五日 近十日 近20日 近40日  自設區間： 從 年 月 日 ∼ 年 月 日 &lt;...</td>\n",
       "      <td>請選擇 近五日 近十日 近20日 近40日  自設區間： 從 年 月 日 ∼ 年 月 日 &lt;...</td>\n",
       "      <td>請選擇 近五日 近十日 近20日 近40日  自設區間： 從 年 月 日 ∼ 年 月 日 &lt;...</td>\n",
       "      <td>請選擇 近五日 近十日 近20日 近40日  自設區間： 從 年 月 日 ∼ 年 月 日 &lt;...</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>4</th>\n",
       "      <td>(自設區間僅提供一年內查詢)</td>\n",
       "      <td>(自設區間僅提供一年內查詢)</td>\n",
       "      <td>(自設區間僅提供一年內查詢)</td>\n",
       "      <td>(自設區間僅提供一年內查詢)</td>\n",
       "      <td>(自設區間僅提供一年內查詢)</td>\n",
       "      <td>(自設區間僅提供一年內查詢)</td>\n",
       "      <td>(自設區間僅提供一年內查詢)</td>\n",
       "      <td>(自設區間僅提供一年內查詢)</td>\n",
       "      <td>(自設區間僅提供一年內查詢)</td>\n",
       "      <td>(自設區間僅提供一年內查詢)</td>\n",
       "      <td>(自設區間僅提供一年內查詢)</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>5</th>\n",
       "      <td>NaN</td>\n",
       "      <td>買賣超</td>\n",
       "      <td>買賣超</td>\n",
       "      <td>買賣超</td>\n",
       "      <td>買賣超</td>\n",
       "      <td>估計持股</td>\n",
       "      <td>估計持股</td>\n",
       "      <td>估計持股</td>\n",
       "      <td>估計持股</td>\n",
       "      <td>持股比重</td>\n",
       "      <td>持股比重</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>6</th>\n",
       "      <td>日期</td>\n",
       "      <td>外資</td>\n",
       "      <td>投信</td>\n",
       "      <td>自營商</td>\n",
       "      <td>單日合計</td>\n",
       "      <td>外資</td>\n",
       "      <td>投信</td>\n",
       "      <td>自營商</td>\n",
       "      <td>單日合計</td>\n",
       "      <td>外資</td>\n",
       "      <td>三大法人</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>7</th>\n",
       "      <td>115/02/06</td>\n",
       "      <td>-54</td>\n",
       "      <td>0</td>\n",
       "      <td>-2</td>\n",
       "      <td>-56</td>\n",
       "      <td>29074</td>\n",
       "      <td>0</td>\n",
       "      <td>1430</td>\n",
       "      <td>30504</td>\n",
       "      <td>18.62%</td>\n",
       "      <td>19.54%</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>8</th>\n",
       "      <td>合計買賣超</td>\n",
       "      <td>-54</td>\n",
       "      <td>0</td>\n",
       "      <td>-2</td>\n",
       "      <td>-56</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "    </tr>\n",
       "  </tbody>\n",
       "</table>\n",
       "</div>"
      ],
      "text/plain": [
       "                                                  0   \\\n",
       "0                                    智冠(5478)法人持股走勢圖   \n",
       "1                                                NaN   \n",
       "2                                     智冠(5478)法人持股明細   \n",
       "3  請選擇 近五日 近十日 近20日 近40日  自設區間： 從 年 月 日 ∼ 年 月 日 <...   \n",
       "4                                     (自設區間僅提供一年內查詢)   \n",
       "5                                                NaN   \n",
       "6                                                 日期   \n",
       "7                                          115/02/06   \n",
       "8                                              合計買賣超   \n",
       "\n",
       "                                                  1   \\\n",
       "0                                    智冠(5478)法人持股走勢圖   \n",
       "1                                                NaN   \n",
       "2                                     智冠(5478)法人持股明細   \n",
       "3  請選擇 近五日 近十日 近20日 近40日  自設區間： 從 年 月 日 ∼ 年 月 日 <...   \n",
       "4                                     (自設區間僅提供一年內查詢)   \n",
       "5                                                買賣超   \n",
       "6                                                 外資   \n",
       "7                                                -54   \n",
       "8                                                -54   \n",
       "\n",
       "                                                  2   \\\n",
       "0                                    智冠(5478)法人持股走勢圖   \n",
       "1                                                NaN   \n",
       "2                                     智冠(5478)法人持股明細   \n",
       "3  請選擇 近五日 近十日 近20日 近40日  自設區間： 從 年 月 日 ∼ 年 月 日 <...   \n",
       "4                                     (自設區間僅提供一年內查詢)   \n",
       "5                                                買賣超   \n",
       "6                                                 投信   \n",
       "7                                                  0   \n",
       "8                                                  0   \n",
       "\n",
       "                                                  3   \\\n",
       "0                                    智冠(5478)法人持股走勢圖   \n",
       "1                                                NaN   \n",
       "2                                     智冠(5478)法人持股明細   \n",
       "3  請選擇 近五日 近十日 近20日 近40日  自設區間： 從 年 月 日 ∼ 年 月 日 <...   \n",
       "4                                     (自設區間僅提供一年內查詢)   \n",
       "5                                                買賣超   \n",
       "6                                                自營商   \n",
       "7                                                 -2   \n",
       "8                                                 -2   \n",
       "\n",
       "                                                  4   \\\n",
       "0                                    智冠(5478)法人持股走勢圖   \n",
       "1                                                NaN   \n",
       "2                                     智冠(5478)法人持股明細   \n",
       "3  請選擇 近五日 近十日 近20日 近40日  自設區間： 從 年 月 日 ∼ 年 月 日 <...   \n",
       "4                                     (自設區間僅提供一年內查詢)   \n",
       "5                                                買賣超   \n",
       "6                                               單日合計   \n",
       "7                                                -56   \n",
       "8                                                -56   \n",
       "\n",
       "                                                  5   \\\n",
       "0                                    智冠(5478)法人持股走勢圖   \n",
       "1                                                NaN   \n",
       "2                                     智冠(5478)法人持股明細   \n",
       "3  請選擇 近五日 近十日 近20日 近40日  自設區間： 從 年 月 日 ∼ 年 月 日 <...   \n",
       "4                                     (自設區間僅提供一年內查詢)   \n",
       "5                                               估計持股   \n",
       "6                                                 外資   \n",
       "7                                              29074   \n",
       "8                                                NaN   \n",
       "\n",
       "                                                  6   \\\n",
       "0                                    智冠(5478)法人持股走勢圖   \n",
       "1                                                NaN   \n",
       "2                                     智冠(5478)法人持股明細   \n",
       "3  請選擇 近五日 近十日 近20日 近40日  自設區間： 從 年 月 日 ∼ 年 月 日 <...   \n",
       "4                                     (自設區間僅提供一年內查詢)   \n",
       "5                                               估計持股   \n",
       "6                                                 投信   \n",
       "7                                                  0   \n",
       "8                                                NaN   \n",
       "\n",
       "                                                  7   \\\n",
       "0                                    智冠(5478)法人持股走勢圖   \n",
       "1                                                NaN   \n",
       "2                                     智冠(5478)法人持股明細   \n",
       "3  請選擇 近五日 近十日 近20日 近40日  自設區間： 從 年 月 日 ∼ 年 月 日 <...   \n",
       "4                                     (自設區間僅提供一年內查詢)   \n",
       "5                                               估計持股   \n",
       "6                                                自營商   \n",
       "7                                               1430   \n",
       "8                                                NaN   \n",
       "\n",
       "                                                  8   \\\n",
       "0                                    智冠(5478)法人持股走勢圖   \n",
       "1                                                NaN   \n",
       "2                                     智冠(5478)法人持股明細   \n",
       "3  請選擇 近五日 近十日 近20日 近40日  自設區間： 從 年 月 日 ∼ 年 月 日 <...   \n",
       "4                                     (自設區間僅提供一年內查詢)   \n",
       "5                                               估計持股   \n",
       "6                                               單日合計   \n",
       "7                                              30504   \n",
       "8                                                NaN   \n",
       "\n",
       "                                                  9   \\\n",
       "0                                    智冠(5478)法人持股走勢圖   \n",
       "1                                                NaN   \n",
       "2                                     智冠(5478)法人持股明細   \n",
       "3  請選擇 近五日 近十日 近20日 近40日  自設區間： 從 年 月 日 ∼ 年 月 日 <...   \n",
       "4                                     (自設區間僅提供一年內查詢)   \n",
       "5                                               持股比重   \n",
       "6                                                 外資   \n",
       "7                                             18.62%   \n",
       "8                                                NaN   \n",
       "\n",
       "                                                  10  \n",
       "0                                    智冠(5478)法人持股走勢圖  \n",
       "1                                                NaN  \n",
       "2                                     智冠(5478)法人持股明細  \n",
       "3  請選擇 近五日 近十日 近20日 近40日  自設區間： 從 年 月 日 ∼ 年 月 日 <...  \n",
       "4                                     (自設區間僅提供一年內查詢)  \n",
       "5                                               持股比重  \n",
       "6                                               三大法人  \n",
       "7                                             19.54%  \n",
       "8                                                NaN  "
      ]
     },
     "execution_count": 24,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "dfs[2]"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 25,
   "id": "0f68459c-2c32-4471-8b49-afa0268f5e6e",
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/html": [
       "<div>\n",
       "<style scoped>\n",
       "    .dataframe tbody tr th:only-of-type {\n",
       "        vertical-align: middle;\n",
       "    }\n",
       "\n",
       "    .dataframe tbody tr th {\n",
       "        vertical-align: top;\n",
       "    }\n",
       "\n",
       "    .dataframe thead th {\n",
       "        text-align: right;\n",
       "    }\n",
       "</style>\n",
       "<table border=\"1\" class=\"dataframe\">\n",
       "  <thead>\n",
       "    <tr style=\"text-align: right;\">\n",
       "      <th></th>\n",
       "      <th>0</th>\n",
       "      <th>1</th>\n",
       "      <th>2</th>\n",
       "      <th>3</th>\n",
       "      <th>4</th>\n",
       "      <th>5</th>\n",
       "      <th>6</th>\n",
       "      <th>7</th>\n",
       "      <th>8</th>\n",
       "      <th>9</th>\n",
       "      <th>10</th>\n",
       "    </tr>\n",
       "  </thead>\n",
       "  <tbody>\n",
       "    <tr>\n",
       "      <th>0</th>\n",
       "      <td></td>\n",
       "      <td>買賣超</td>\n",
       "      <td>買賣超</td>\n",
       "      <td>買賣超</td>\n",
       "      <td>買賣超</td>\n",
       "      <td>估計持股</td>\n",
       "      <td>估計持股</td>\n",
       "      <td>估計持股</td>\n",
       "      <td>估計持股</td>\n",
       "      <td>持股比重</td>\n",
       "      <td>持股比重</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>1</th>\n",
       "      <td>日期</td>\n",
       "      <td>外資</td>\n",
       "      <td>投信</td>\n",
       "      <td>自營商</td>\n",
       "      <td>單日合計</td>\n",
       "      <td>外資</td>\n",
       "      <td>投信</td>\n",
       "      <td>自營商</td>\n",
       "      <td>單日合計</td>\n",
       "      <td>外資</td>\n",
       "      <td>三大法人</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>2</th>\n",
       "      <td>115/02/06</td>\n",
       "      <td>-54</td>\n",
       "      <td>0</td>\n",
       "      <td>-2</td>\n",
       "      <td>-56</td>\n",
       "      <td>29074</td>\n",
       "      <td>0</td>\n",
       "      <td>1430</td>\n",
       "      <td>30504</td>\n",
       "      <td>18.62%</td>\n",
       "      <td>19.54%</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>3</th>\n",
       "      <td>合計買賣超</td>\n",
       "      <td>-54</td>\n",
       "      <td>0</td>\n",
       "      <td>-2</td>\n",
       "      <td>-56</td>\n",
       "      <td></td>\n",
       "      <td></td>\n",
       "      <td></td>\n",
       "      <td></td>\n",
       "      <td></td>\n",
       "      <td></td>\n",
       "    </tr>\n",
       "  </tbody>\n",
       "</table>\n",
       "</div>"
      ],
      "text/plain": [
       "          0    1    2    3     4      5     6     7      8       9       10\n",
       "0             買賣超  買賣超  買賣超   買賣超   估計持股  估計持股  估計持股   估計持股    持股比重    持股比重\n",
       "1         日期   外資   投信  自營商  單日合計     外資    投信   自營商   單日合計      外資    三大法人\n",
       "2  115/02/06  -54    0   -2   -56  29074     0  1430  30504  18.62%  19.54%\n",
       "3      合計買賣超  -54    0   -2   -56                                          "
      ]
     },
     "execution_count": 25,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "#剔除前面的6行的資料\n",
    "df = dfs[2].iloc[5:].reset_index(drop=True)\n",
    "df = df.fillna('')\n",
    "df"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 26,
   "id": "a72d084c-cb7a-4b6a-914d-2dac49a77cdf",
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/html": [
       "<div>\n",
       "<style scoped>\n",
       "    .dataframe tbody tr th:only-of-type {\n",
       "        vertical-align: middle;\n",
       "    }\n",
       "\n",
       "    .dataframe tbody tr th {\n",
       "        vertical-align: top;\n",
       "    }\n",
       "\n",
       "    .dataframe thead th {\n",
       "        text-align: right;\n",
       "    }\n",
       "</style>\n",
       "<table border=\"1\" class=\"dataframe\">\n",
       "  <thead>\n",
       "    <tr style=\"text-align: right;\">\n",
       "      <th></th>\n",
       "      <th>0</th>\n",
       "      <th>1</th>\n",
       "      <th>2</th>\n",
       "      <th>3</th>\n",
       "      <th>4</th>\n",
       "      <th>5</th>\n",
       "      <th>6</th>\n",
       "      <th>7</th>\n",
       "      <th>8</th>\n",
       "      <th>9</th>\n",
       "      <th>10</th>\n",
       "    </tr>\n",
       "  </thead>\n",
       "  <tbody>\n",
       "    <tr>\n",
       "      <th>0</th>\n",
       "      <td></td>\n",
       "      <td>買賣超</td>\n",
       "      <td>買賣超</td>\n",
       "      <td>買賣超</td>\n",
       "      <td>買賣超</td>\n",
       "      <td>估計持股</td>\n",
       "      <td>估計持股</td>\n",
       "      <td>估計持股</td>\n",
       "      <td>估計持股</td>\n",
       "      <td>持股比重</td>\n",
       "      <td>持股比重</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>1</th>\n",
       "      <td>日期</td>\n",
       "      <td>外資</td>\n",
       "      <td>投信</td>\n",
       "      <td>自營商</td>\n",
       "      <td>單日合計</td>\n",
       "      <td>外資</td>\n",
       "      <td>投信</td>\n",
       "      <td>自營商</td>\n",
       "      <td>單日合計</td>\n",
       "      <td>外資</td>\n",
       "      <td>三大法人</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>2</th>\n",
       "      <td>115/02/06</td>\n",
       "      <td>-54</td>\n",
       "      <td>0</td>\n",
       "      <td>-2</td>\n",
       "      <td>-56</td>\n",
       "      <td>29,074</td>\n",
       "      <td>0</td>\n",
       "      <td>1,430</td>\n",
       "      <td>30,504</td>\n",
       "      <td>18.62%</td>\n",
       "      <td>19.54%</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>3</th>\n",
       "      <td>合計買賣超</td>\n",
       "      <td>-54</td>\n",
       "      <td>0</td>\n",
       "      <td>-2</td>\n",
       "      <td>-56</td>\n",
       "      <td></td>\n",
       "      <td></td>\n",
       "      <td></td>\n",
       "      <td></td>\n",
       "      <td></td>\n",
       "      <td></td>\n",
       "    </tr>\n",
       "  </tbody>\n",
       "</table>\n",
       "</div>"
      ],
      "text/plain": [
       "          0    1    2    3     4       5     6      7       8       9       10\n",
       "0             買賣超  買賣超  買賣超   買賣超    估計持股  估計持股   估計持股    估計持股    持股比重    持股比重\n",
       "1         日期   外資   投信  自營商  單日合計      外資    投信    自營商    單日合計      外資    三大法人\n",
       "2  115/02/06  -54    0   -2   -56  29,074     0  1,430  30,504  18.62%  19.54%\n",
       "3      合計買賣超  -54    0   -2   -56                                             "
      ]
     },
     "execution_count": 26,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "#數值表示為千分位\n",
    "def format_thousands(x):\n",
    "    try:\n",
    "        return f\"{int(x):,}\"\n",
    "    except:\n",
    "        return x  # 保留非數值或空字串\n",
    "\n",
    "df = df.map(format_thousands)\n",
    "df"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 27,
   "id": "fa3c9f7c-13da-4de6-a463-bd32f3160409",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "回寫完成\n"
     ]
    }
   ],
   "source": [
    "#寫回檔案\n",
    "sheet_sw=wb_sw.sheets[0]\n",
    "sheet_sw.range('F4').options(index=False, header=False).value = df\n",
    "print(\"回寫完成\")"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 28,
   "id": "7b1dff3c-bdf1-4be2-b417-5c45fff8fe58",
   "metadata": {},
   "outputs": [],
   "source": [
    "# 加框線：Excel 的邊框代碼 7=外框, 9=內框 \n",
    "last_row = sheet_sw.range('F4').expand().last_cell.row \n",
    "last_col = sheet_sw.range('F4').expand().last_cell.column \n",
    "data_range = sheet_sw.range((3, 6), (last_row, last_col)) # (row, col) \n",
    "\n",
    "for border_id in [7,8,9,10,11,12]:\n",
    "    data_range.api.Borders(border_id).LineStyle = 1 # 實線 \n",
    "    data_range.api.Borders(border_id).Weight = 2 # 粗細 (2=中等)"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "c5aa992d-1b9f-46c3-8d6a-00f259b8f3c7",
   "metadata": {},
   "source": [
    "玩股網截圖"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 29,
   "id": "3e437664-17b8-4024-8c58-77cd14332cad",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "沒有廣告或找不到關閉按鈕\n",
      "玩股網截圖貼上完成\n"
     ]
    }
   ],
   "source": [
    "from selenium import webdriver\n",
    "from selenium.webdriver.common.keys import Keys\n",
    "from selenium.webdriver.common.by import By\n",
    "import time \n",
    "import undetected_chromedriver as uc\n",
    "from bs4 import BeautifulSoup\n",
    "\n",
    "driver = uc.Chrome()\n",
    "url =f\"https://www.wantgoo.com/stock/5478\"\n",
    "driver.get(url)\n",
    "try:\n",
    "    ad_close = WebDriverWait(driver, 5).until(\n",
    "        EC.element_to_be_clickable((By.CLASS_NAME, \"close-btn\"))\n",
    "    )\n",
    "    ad_close.click()\n",
    "except:\n",
    "    print(\"沒有廣告或找不到關閉按鈕\")\n",
    "\n",
    "\n",
    "driver.get(url)\n",
    "time.sleep(10)\n",
    "pic1=driver.find_element(By.CLASS_NAME,'quotes-hd')\n",
    "pic1.screenshot('./a1.png')\n",
    "pic2=driver.find_element(By.CLASS_NAME,'quotes-info')\n",
    "pic2.screenshot('./a2.png')\n",
    "pic3=driver.find_element(By.CLASS_NAME,'title')\n",
    "pic3.screenshot('./a3.png')\n",
    "pic4=driver.find_element(By.CLASS_NAME,'realtime-card')\n",
    "pic4.screenshot('./a4.png')\n",
    "\n",
    "driver.close()\n",
    "sheet_sw=wb_sw.sheets[0]\n",
    "\n",
    "import os\n",
    "file_path = os.path.abspath(\"./a1.png\")\n",
    "sheet_sw.pictures.add(\n",
    "    file_path,\n",
    "    name=\"pic_a1\",   # 指定名稱，方便 update\n",
    "    update=True,\n",
    "    left=sheet_sw.range(\"F26\").left,\n",
    "    top=sheet_sw.range(\"F26\").top\n",
    ")\n",
    "\n",
    "file_path2 = os.path.abspath(\"./a2.png\")\n",
    "sheet_sw.pictures.add(\n",
    "    file_path2,\n",
    "    name=\"pic_a2\",   # 指定名稱，方便 update\n",
    "    update=True,\n",
    "    left=sheet_sw.range(\"F28\").left,\n",
    "    top=sheet_sw.range(\"F28\").top\n",
    ")\n",
    "file_path3 = os.path.abspath(\"./a3.png\")\n",
    "sheet_sw.pictures.add(\n",
    "    file_path3,\n",
    "    name=\"pic_a3\",   # 指定名稱，方便 update\n",
    "    update=True,\n",
    "    left=sheet_sw.range(\"F32\").left,\n",
    "    top=sheet_sw.range(\"F32\").top\n",
    ")\n",
    "file_path4 = os.path.abspath(\"./a4.png\")\n",
    "sheet_sw.pictures.add(\n",
    "    file_path4,\n",
    "    name=\"pic_a4\",   # 指定名稱，方便 update\n",
    "    update=True,\n",
    "    left=sheet_sw.range(\"F34\").left,\n",
    "    top=sheet_sw.range(\"F34\").top\n",
    ")\n",
    "print(\"玩股網截圖貼上完成\")"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 30,
   "id": "e79fd164-4f3c-4055-930b-f387aeba71bf",
   "metadata": {},
   "outputs": [],
   "source": [
    "wb_sw.save() \n",
    "wb_sw.close()              "
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 31,
   "id": "c9f888d0-a1c5-4ea8-b783-82e3b018ca01",
   "metadata": {},
   "outputs": [],
   "source": [
    "#def format_negative(val):\n",
    "    #if val < 0: \n",
    "       # return f\"<span style='color:red'>({abs(val):,})</span>\"\n",
    "        #return f\"{val:,}\"\n",
    "    #else:\n",
    "        #return f\"{val:,}\"\n",
    "        \n",
    "#styled_df= filtered.style.format({'加總net': format_negative})\n",
    "#styled_df"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 32,
   "id": "25678829-70af-459a-8680-8984382d56d6",
   "metadata": {},
   "outputs": [],
   "source": [
    "# step 7 定義數值顯示格式\n",
    "#def format_negative(val):\n",
    "    #if val < 0: \n",
    "       # return f\"<span style='color:red'>({abs(val):,})</span>\"\n",
    "        #return f\"{val:,}\"\n",
    "   # else:\n",
    "        #return f\"{val:,}\"\n",
    "#styled_df= df.style.format({\n",
    "    #'加總-買進股數': format_negative,\n",
    "    #'加總-賣出股數': format_negative,\n",
    "    #'加總net': format_negative\n",
    "#})"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3 (ipykernel)",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.14.0"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
